/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:459aed75-4884-4449-8f62-7bf5f3f58e57",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_sjP0Kyen1",
    "aws_user_pools_web_client_id": "529gqvt4bjkeih0pgir749ubbd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dfft4jjjwzadrdipqfbrbbxuj4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7rbvhzo54vhnzan3bpb764udpq"
};


export default awsmobile;
